### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/Nick#1]
- [ ] Don't allow using special characters, make it work like Minecrafts' names.

- [ ] Fix grammar / spelling in the plugin

- [ ] Optttttimize da code
